name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove release
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          gh release delete release --cleanup-tag -y
          git tag -d release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        run: |
          git tag release
          git push origin --tags
          pushd public
          zip -r ../dist.zip *
          popd
          gh release create release --latest dist.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: build
    uses: NKID00/nkid00.name/.github/workflows/deploy.yml@master
    secrets: inherit
