name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          path: public/
  deploy:
    uses: NKID00/nkid00.name-priv/.github/workflows/deploy.yml@workflow
    secrets: inherit
