name: deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve current time
        run: |
          echo "TIME=$(date --iso-8601=seconds --utc)" >> ${GITHUB_ENV}
      - name: Configure git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: NKID00/nkid00.name-priv
          ref: master
          token: ${{ secrets.GH_PAT }}
          path: .
      - name: Create branch dist
        run: |
          git checkout --orphan dist
      - name: Download artifact from NKID00/nkid00.name
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GH_PAT }}
          workflow: build.yml
          workflow_conclusion: ""
          branch: master
          name: artifact
          path: home/
          repo: NKID00/nkid00.name
      - name: Download artifact from NKID00/dazhuan-assignments
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GH_PAT }}
          workflow: build.yml
          workflow_conclusion: ""
          branch: master
          name: artifact
          path: assignments/
          repo: NKID00/dazhuan-assignments
      - name: Download artifact from NKID00/tic-tac-toe
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GH_PAT }}
          workflow: build.yml
          workflow_conclusion: ""
          branch: master
          name: artifact
          path: tic-tac-toe/
          repo: NKID00/tic-tac-toe
      - name: Commit and push branch dist
        run: |
          git add .
          git commit -q -m "${{ env.TIME }}"
          git push --force origin dist:dist
