name: deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve current time
        run: |
          echo "TIME=$(date --iso-8601=seconds --utc)" >> ${GITHUB_ENV}
      - name: Configure git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: NKID00/nkid00.name-priv
          ref: master
          token: ${{ secrets.GH_PAT }}
          path: .
      - name: Create branch dist
        run: |
          git checkout --orphan dist
      - name: Download artifacts
        run: |
          gh release download -R NKID00/nkid00.name -p dist.zip -o artifact/home.zip
          gh release download -R NKID00/journal -p dist.zip -o artifact/journal.zip
          gh release download -R NKID00/dazhuan-assignments -p dist.zip -o artifact/assignments.zip
          gh release download -R NKID00/tic-tac-toe -p dist.zip -o artifact/tic-tac-toe.zip
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      - name: Extract artifacts
        run: |
          for f in artifact/*.zip
          do unzip -q "$f" -d `basename "$f" .zip`
          done
          rm -r artifact
      - name: Commit and push branch dist
        run: |
          git add .
          git commit -q -m "${{ env.TIME }}"
          git push --force origin dist:dist
